# Generated by Django 3.2.3 on 2021-05-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('datacriacao', models.DateTimeField(auto_now_add=True)),
                ('dataatualizacao', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7)),
            ],
        ),
    ]
