# Generated by Django 3.2.3 on 2021-05-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='dataatualizacao',
        ),
        migrations.RemoveField(
            model_name='check',
            name='datacriacao',
        ),
    ]
