# Generated by Django 3.2.3 on 2021-05-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20210515_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='Evento',
        ),
    ]
