# Generated by Django 3.2.3 on 2021-05-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_rename_check_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateTimeField(auto_now_add=True)),
                ('dataatualizacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Check_Evento', to='checklist.evento')),
            ],
        ),
    ]
