# Generated by Django 3.2.3 on 2021-05-15 22:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_check'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='check',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
