# Generated by Django 3.2.3 on 2021-05-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_check_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nivel',
            field=models.CharField(choices=[('basico', 'Básico'), ('medio', 'Médio'), ('avanc', 'Avançado')], default='basico', max_length=6),
        ),
    ]
