# Generated by Django 3.2.3 on 2021-05-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_evento_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tarefa',
            field=models.TextField(null=True),
        ),
    ]
