# Generated by Django 3.2.3 on 2021-05-17 00:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_evento_tarefa'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='evento',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
